version: '3.8'
services:

  postgres:
    ports:
      - "54321:5432"

  elastic:
    ports:
      - "9201:9200"

  redis:
    ports:
      - "63791:6379"

  fastapi:
    ports:
      - "8080:80"

  admin:
    ports:
      - "8000:8000"

  auth:
    ports:
      - "5000:5000"

  jaeger:
    ports:
      - "16686:16686"
      - "6831:6831/udp"