# Generated by Django 4.1.2 on 2022-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_filmwork_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personfilmwork',
            name='film_work_person_idx',
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'person', 'role'), name='film_work_person_idx'),
        ),
    ]
